import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from './header'
import Options from './registered_user/options'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FpTrack App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
    <Header></Header>
    <Options></Options>
    </div>
  )
}
